<a href="https://colab.research.google.com/github/navinprasanth-tech/AI_workforce_pandas/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving employee_birthdates.csv to employee_birthdates (1).csv

In [ ]:
df = pd.read_csv("employee_birthdates.csv")

df.head()

   employee_id  birth_date
0            1   1/18/2003
1            2  12/14/1982
2            3   1/11/2002
3            4  10/29/1972
4            5    8/8/1989

In [ ]:
df["birth_date"] = pd.to_datetime(df["birth_date"])

In [ ]:
df["birth_year"] = df["birth_date"].dt.year

df.head()

   employee_id birth_date  birth_year
0            1 2003-01-18        2003
1            2 1982-12-14        1982
2            3 2002-01-11        2002
3            4 1972-10-29        1972
4            5 1989-08-08        1989

In [ ]:
oldest_three = df.sort_values(by="birth_date").head(3)

oldest_three[["employee_id", "birth_date"]]

    employee_id birth_date
81           82 1970-08-30
16           17 1972-03-22
26           27 1972-07-04

In [ ]:
birth_year_count = df["birth_year"].value_counts().sort_index()

print(birth_year_count)

birth_year
1970    1
1972    4
1973    3
1974    2
1975    3
1976    3
1978    3
1979    6
1980    6
1981    4
1982    3
1983    2
1984    4
1985    4
1986    5
1987    4
1988    1
1989    4
1990    2
1991    5
1992    2
1993    2
1994    1
1995    3
1996    3
1997    1
1998    1
1999    5
2000    1
2001    2
2002    2
2003    5
2004    3
Name: count, dtype: int64

In [ ]:
born_after_1990 = df[df["birth_year"] > 1990]

print(born_after_1990)

    employee_id birth_date  birth_year
0             1 2003-01-18        2003
2             3 2002-01-11        2002
5             6 1995-02-02        1995
6             7 2001-01-08        2001
7             8 1994-08-04        1994
10           11 1997-12-13        1997
18           19 1991-10-06        1991
21           22 2001-02-04        2001
23           24 1991-03-01        1991
31           32 2002-01-02        2002
32           33 1999-07-02        1999
34           35 2000-09-15        2000
37           38 1991-01-19        1991
38           39 2003-10-13        2003
41           42 2003-12-15        2003
42           43 1993-06-22        1993
44           45 1998-06-20        1998
46           47 1999-12-26        1999
53           54 1996-07-20        1996
55           56 2004-01-19        2004
59           60 1999-10-06        1999
61           62 1996-02-25        1996
65           66 1999-11-12        1999
71           72 1991-03-18        1991
73           74 1995-10-21        1995
80           81 1992-06-15        1992
83           84 1996-10-19        1996
85           86 2004-09-24        2004
86           87 1992-10-26        1992
88           89 1995-06-07        1995
90           91 2003-09-28        2003
91           92 1999-11-12        1999
92           93 2003-04-19        2003
94           95 1993-07-30        1993
96           97 2004-05-01        2004
98           99 1991-03-08        1991

In [ ]:
today = pd.Timestamp.today()

df["age"] = today.year - df["birth_date"].dt.year

df.loc[
    (df["birth_date"].dt.month > today.month) |
    (
        (df["birth_date"].dt.month == today.month) &
        (df["birth_date"].dt.day > today.day)
    ),
    "age"
] -= 1

df[["employee_id", "birth_date", "age"]]

    employee_id birth_date  age
0             1 2003-01-18   23
1             2 1982-12-14   43
2             3 2002-01-11   24
3             4 1972-10-29   53
4             5 1989-08-08   37
..          ...        ...  ...
95           96 1973-03-15   53
96           97 2004-05-01   22
97           98 1986-09-14   39
98           99 1991-03-08   35
99          100 1973-05-06   53

[100 rows x 3 columns]